
replicaCount: 3

image:
  repository: us-central1-docker.pkg.dev/project-ostafii/artemis/artemis
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.0.0"

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: dev-atremis.ostafon.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: dev-artemis-tls
      hosts:
        - dev-atremis.ostafon.com